# shellcheck shell=bash
# lib/features/root_unlock.sh — menu 13: root-drive unlock (clevis-initramfs)
#
# See docs/future-work.md for the full design. This file starts with
# the pure, read-only safety-check primitives the wizard depends on --
# no mutation, no whiptail -- built and tested first, before any of the
# actual bind/initramfs-regeneration logic that touches boot-critical
# state.

# resolve_root_luks_device — the crypto_LUKS device backing the
# current root filesystem, walking up through any LVM layers, or
# empty if root isn't LUKS-encrypted at all. Never cached: resolved
# fresh every call, matching this project's device-resolution rule
# (see lib/core/device.sh).
#
# Confirmed on real hardware: `lsblk -no PKNAME <device>` does not
# reliably resolve a single device's parent in isolation (it depends
# on lsblk being asked to show the whole topology) -- this walks the
# full JSON tree instead, tracking every crypto_LUKS ancestor seen on
# the way down and returning the closest one to the target, if any.
resolve_root_luks_device() {
    local src target
    src="$(findmnt -no SOURCE / 2>/dev/null)"
    [[ -n "$src" ]] || return 0
    target="$(basename "$src")"

    lsblk --json -o NAME,FSTYPE 2>/dev/null | python3 -c '
import json, sys

def find_luks_ancestor(node, target, luks_stack):
    name = node.get("name")
    is_luks = node.get("fstype") == "crypto_LUKS"
    new_stack = luks_stack + [name] if is_luks else luks_stack
    if name == target:
        return new_stack[-1] if new_stack else None
    for child in node.get("children", []):
        result = find_luks_ancestor(child, target, new_stack)
        if result is not None:
            return result
    return None

data = json.load(sys.stdin)
target = sys.argv[1]
for dev in data.get("blockdevices", []):
    result = find_luks_ancestor(dev, target, [])
    if result:
        print("/dev/" + result)
        break
' "$target"
    return 0
}

# is_boot_separate_from_root — true if /boot is its own mountpoint,
# distinct from /.
#
# Confirmed on real hardware: Ubuntu's default encrypted-install
# layout keeps /boot as its own plain, unencrypted partition entirely
# outside the LUKS volume -- GRUB never decrypts anything itself, it
# just reads the kernel/initrd normally from plain /boot, and all
# decryption happens later, inside the already-loaded initramfs. An
# earlier version of this design assumed GRUB_ENABLE_CRYPTODISK needed
# checking; that's only relevant in the uncommon case where /boot
# itself lives inside the encrypted volume, which this check detects.
is_boot_separate_from_root() {
    local root_src boot_src
    root_src="$(findmnt -no SOURCE / 2>/dev/null)"
    boot_src="$(findmnt -no SOURCE /boot 2>/dev/null)"
    [[ -n "$boot_src" && "$boot_src" != "$root_src" ]]
}

# is_tpm2_present — true if a TPM2 device node exists.
is_tpm2_present() {
    [[ -e /dev/tpmrm0 || -e /dev/tpm0 ]]
}

# is_local_address <host> — true if <host> is loopback, or resolves to
# any address currently assigned to one of this machine's own network
# interfaces.
#
# Used to hard-block a same-host Tang dependency for root unlock: Tang
# runs as a systemd service, which can't start until the real root
# filesystem is already mounted, and root can't mount until it's
# unlocked -- a same-host Tang address can never work, regardless of
# whether it's technically reachable. Not a reachability question, a
# bootstrapping impossibility, so this is a hard block, not a warning.
is_local_address() {
    local host="$1"
    case "$host" in
        127.*|::1|localhost) return 0 ;;
    esac

    local resolved
    resolved="$(getent hosts "$host" 2>/dev/null | awk '{print $1; exit}')"
    [[ -n "$resolved" ]] || resolved="$host"

    # Re-check after resolution too: a hostname can resolve to loopback
    # (e.g. /etc/hosts mapping it to 127.0.0.1) even when the literal
    # input didn't look like loopback itself.
    case "$resolved" in
        127.*|::1) return 0 ;;
    esac

    local local_ip
    while IFS= read -r local_ip; do
        [[ -n "$local_ip" ]] || continue
        [[ "$local_ip" == "$resolved" ]] && return 0
    done < <(ip -o addr show scope global 2>/dev/null | awk '{print $4}' | cut -d/ -f1)
    return 1
}

# --- Recovery kit ------------------------------------------------------
#
# Generated by Enable (first bind), Disable (revert), and on-demand by
# Snapshot. Split across two locations (see docs/future-work.md for
# why): the small guide + self-contained script live on /boot (its own
# unencrypted partition, readable even if root never unlocks at all);
# the multi-megabyte initramfs backup itself lives under /root
# (restoring it needs write access to /boot anyway, which is only
# available once root is reachable one way or another).
#
# Each kit is its own timestamped subdirectory -- never overwritten,
# pruned by count via prune_recovery_kits -- with a "latest" symlink in
# each location pointing at the newest one.

: "${WARDEN_ROOT_UNLOCK_BOOT_DIR:=/boot/warden-root-unlock-recovery}"
: "${WARDEN_ROOT_UNLOCK_ROOT_DIR:=/root/warden-root-unlock-recovery}"
: "${WARDEN_ROOT_UNLOCK_RETAIN:=3}"

# has_enough_disk_space <path> <needed_bytes> — checks the filesystem
# backing <path> (which need not exist yet -- checks its parent) has
# at least <needed_bytes> free. Initramfs backups are tens of
# megabytes, not the KB-sized text files Warden backs up everywhere
# else, so this is checked explicitly rather than assumed to always
# succeed.
has_enough_disk_space() {
    local path="$1" needed_bytes="$2" check_dir avail_kb avail_bytes
    check_dir="$path"
    while [[ ! -d "$check_dir" && "$check_dir" != "/" ]]; do
        check_dir="$(dirname "$check_dir")"
    done
    avail_kb="$(df -Pk "$check_dir" 2>/dev/null | awk 'NR==2 {print $4}')"
    [[ -n "$avail_kb" ]] || return 1
    avail_bytes=$((avail_kb * 1024))
    [[ "$avail_bytes" -ge "$needed_bytes" ]]
}

# generate_recovery_guide_text <timestamp> <hostname> <root_uuid>
#   <boot_uuid> <kernel_version> <boot_kit_dir> <root_backup_file>
#   <target_initrd>
#
# Pure function: prints the guide text, writes nothing. Every value is
# baked in at generation time -- no placeholders, nothing to guess or
# adapt while reading this under pressure. Only mounts root and /boot:
# restoring an initramfs file never needs /boot/efi, so it's left out
# rather than adding a step (and a device to identify) that isn't
# actually necessary here.
generate_recovery_guide_text() {
    local ts="$1" hostname="$2" root_uuid="$3" boot_uuid="$4" kernel="$5" boot_kit_dir="$6" root_backup="$7" target="$8"
    cat <<EOF
WARDEN ROOT-DRIVE UNLOCK -- EMERGENCY RECOVERY GUIDE
Generated: ${ts}
Machine:   ${hostname}
Root UUID: ${root_uuid}
Kernel:    ${kernel}

WHAT THIS IS
------------
Warden changed this machine's boot process to unlock its root drive
automatically via Clevis (Tang and/or a TPM2 chip), instead of only
ever prompting for a passphrase. Before doing so, it backed up the
initramfs image that was in place immediately beforehand. This guide
and the accompanying restore.sh exist to undo that specific change if
something about it leaves this machine unable to boot normally.

This snapshot reflects the system as of ${ts}. If kernel or package
updates have happened since, restoring it will also undo those, not
just whatever is currently broken -- it is not a general-purpose
backup, only a rollback for this one change.

YOUR PASSPHRASE STILL WORKS
----------------------------
Enabling this feature never removes the original LUKS passphrase. If
the machine still reaches the normal boot prompt, typing that
passphrase unlocks it exactly as it always did, whether or not the
automatic unlock is working.

IF THE MACHINE WON'T BOOT AT ALL
---------------------------------
Boot from separate rescue/recovery media (a live Ubuntu image, or
similar), then:

1. Unlock and mount the encrypted root manually:
     cryptsetup open --type luks UUID=${root_uuid} recovery-root
     (enter the LUKS passphrase when prompted)
     mkdir -p /mnt/recovery
     mount /dev/mapper/recovery-root /mnt/recovery
     mount UUID=${boot_uuid} /mnt/recovery/boot

   (/boot/efi does not need mounting -- restoring the initramfs file
   only touches /boot itself.)

2. Either run the accompanying script from a chroot:
     cp ${boot_kit_dir}/restore.sh /mnt/recovery/tmp/restore.sh
     chroot /mnt/recovery /tmp/restore.sh

   Or restore by hand:
     cp -p ${root_backup} /mnt/recovery${target}
     (then reboot)

WHERE THIS KIT LIVES
---------------------
Guide + script (this directory, on /boot, reachable even if root
never unlocks): ${boot_kit_dir}
Initramfs backup itself (on /root, inside the encrypted volume):
${root_backup}

This is operationally important, not secret -- there is nothing
confidential in it. The concern is losing it, not it being read; don't
let routine cleanup delete it.
EOF
}

# generate_recovery_script_text <timestamp> <backup_file> <target_file>
#   <kernel_version>
#
# Pure function: prints the self-contained recovery script, writes
# nothing. Deliberately has no dependency on Warden's own lib/ being
# sourceable -- it needs to work from a rescue environment where the
# real root filesystem (and Warden's code with it) might not be
# mounted at all. Every value is baked in, nothing computed or guessed
# at recovery time.
generate_recovery_script_text() {
    local ts="$1" backup_file="$2" target_file="$3" kernel="$4"
    cat <<EOF
#!/usr/bin/env bash
# Warden root-unlock recovery script -- generated ${ts}
# Restores the initramfs backup taken just before root-drive unlock
# was enabled via Clevis. See the accompanying GUIDE.txt.
set -euo pipefail

BACKUP_FILE="${backup_file}"
TARGET_FILE="${target_file}"
EXPECTED_KERNEL="${kernel}"
GENERATED="${ts}"

echo "Warden root-unlock recovery script"
echo "Generated: \${GENERATED}"
echo

CURRENT_KERNEL="\$(uname -r 2>/dev/null || echo unknown)"
echo "Currently running kernel: \${CURRENT_KERNEL}"
echo "This backup targets kernel: \${EXPECTED_KERNEL}"
echo

if [[ "\$CURRENT_KERNEL" == "\$EXPECTED_KERNEL" ]]; then
    echo "WARNING: you are running this from a normally-booted system,"
    echo "on the SAME kernel this backup targets. If this system is"
    echo "working normally, there is likely nothing to restore --"
    echo "double check before continuing."
    echo
fi

if [[ ! -f "\$BACKUP_FILE" ]]; then
    echo "ERROR: backup file not found at \${BACKUP_FILE}." >&2
    echo "If you're running this from rescue media, make sure the real" >&2
    echo "root filesystem is mounted at the expected location first." >&2
    exit 1
fi

echo "Backup file:  \${BACKUP_FILE} (\$(du -h "\$BACKUP_FILE" 2>/dev/null | cut -f1))"
if [[ -f "\$TARGET_FILE" ]]; then
    echo "Target file:  \${TARGET_FILE} (\$(du -h "\$TARGET_FILE" 2>/dev/null | cut -f1), modified \$(date -r "\$TARGET_FILE" 2>/dev/null))"
else
    echo "Target file:  \${TARGET_FILE} (does not currently exist)"
fi
echo
echo "This will overwrite \${TARGET_FILE} with the backup above."
echo "The current file, if any, is backed up first, alongside itself."
echo
read -r -p "Type RESTORE (all capitals) to proceed, anything else to cancel: " CONFIRM
if [[ "\$CONFIRM" != "RESTORE" ]]; then
    echo "Cancelled -- nothing was changed."
    exit 0
fi

if [[ -f "\$TARGET_FILE" ]]; then
    PRE_RESTORE_BACKUP="\${TARGET_FILE}.pre-restore-\$(date -u +%Y%m%dT%H%M%SZ)"
    cp -p "\$TARGET_FILE" "\$PRE_RESTORE_BACKUP"
    echo "Backed up the current file to: \${PRE_RESTORE_BACKUP}"
fi

cp -p "\$BACKUP_FILE" "\$TARGET_FILE"
echo "Restored \${TARGET_FILE} from \${BACKUP_FILE}. Reboot to use it."
EOF
}

# prune_recovery_kits <dir> <retain_count> — deletes the oldest
# timestamped subdirectories of <dir> beyond <retain_count>, by name
# (timestamps sort lexicographically), never below 1. Logs what it
# removes. Used identically for both the /boot and /root kit
# directories.
prune_recovery_kits() {
    local dir="$1" retain="$2"
    [[ -d "$dir" ]] || return 0

    local -a kits=()
    local entry
    while IFS= read -r entry; do
        [[ -n "$entry" ]] || continue
        kits+=("$entry")
    done < <(find "$dir" -mindepth 1 -maxdepth 1 -type d -name '20*' | sort)

    local total="${#kits[@]}"
    [[ "$retain" -lt 1 ]] && retain=1
    [[ "$total" -le "$retain" ]] && return 0

    local remove_count=$((total - retain))
    local i
    for ((i = 0; i < remove_count; i++)); do
        log_line "ROOT-UNLOCK: pruning old recovery kit ${kits[$i]} (retention: ${retain})"
        rm -rf "${kits[$i]}"
    done
}

# create_root_unlock_recovery_kit <source_initramfs_path>
#
# Orchestrates a full recovery kit: backs up <source_initramfs_path>
# under WARDEN_ROOT_UNLOCK_ROOT_DIR, writes the guide + self-contained
# script under WARDEN_ROOT_UNLOCK_BOOT_DIR, maintains a "latest"
# symlink in each location, and prunes old kits beyond
# WARDEN_ROOT_UNLOCK_RETAIN. Prints the new kit's timestamp on success.
#
# Checks available disk space before touching anything: an initramfs
# backup is tens of megabytes, not the KB-sized text files backed up
# everywhere else in Warden, so this is verified rather than assumed.
create_root_unlock_recovery_kit() {
    local source_initramfs="$1"
    if [[ ! -f "$source_initramfs" ]]; then
        log_line "ROOT-UNLOCK: cannot back up ${source_initramfs}, file not found"
        return 1
    fi

    local needed_bytes
    needed_bytes="$(stat -c '%s' "$source_initramfs" 2>/dev/null)"
    needed_bytes="${needed_bytes:-0}"
    needed_bytes=$((needed_bytes + 5 * 1024 * 1024))

    if ! has_enough_disk_space "$WARDEN_ROOT_UNLOCK_ROOT_DIR" "$needed_bytes"; then
        log_line "ROOT-UNLOCK: not enough space near ${WARDEN_ROOT_UNLOCK_ROOT_DIR} for a new recovery kit"
        return 1
    fi
    if ! has_enough_disk_space "$WARDEN_ROOT_UNLOCK_BOOT_DIR" $((1024 * 1024)); then
        log_line "ROOT-UNLOCK: not enough space near ${WARDEN_ROOT_UNLOCK_BOOT_DIR} for a new recovery kit"
        return 1
    fi

    local ts hostname_val kernel root_uuid boot_uuid
    ts="$(date -u +%Y%m%dT%H%M%SZ)"
    hostname_val="$(hostname 2>/dev/null || echo unknown-host)"
    kernel="$(basename "$source_initramfs" | sed 's/^initrd\.img-//')"
    root_uuid="$(findmnt -no UUID / 2>/dev/null)"
    [[ -n "$root_uuid" ]] || root_uuid="unknown"
    boot_uuid="$(findmnt -no UUID /boot 2>/dev/null)"
    [[ -n "$boot_uuid" ]] || boot_uuid="unknown"

    local boot_kit_dir="${WARDEN_ROOT_UNLOCK_BOOT_DIR}/${ts}"
    local root_kit_dir="${WARDEN_ROOT_UNLOCK_ROOT_DIR}/${ts}"
    local backup_file="${root_kit_dir}/initrd.img.bak"
    local target_file="$source_initramfs"

    if [[ "${WARDEN_DRY_RUN}" == "1" ]]; then
        log_line "[DRY-RUN] would create recovery kit ${ts}: back up ${source_initramfs} to ${backup_file}, write guide+script under ${boot_kit_dir}"
        printf '[DRY-RUN] would create recovery kit %s\n' "$ts" >&2
        printf '%s' "$ts"
        return 0
    fi

    mkdir -p "$boot_kit_dir" "$root_kit_dir"
    chmod 700 "$root_kit_dir"

    cp -p "$source_initramfs" "$backup_file"

    generate_recovery_guide_text "$ts" "$hostname_val" "$root_uuid" "$boot_uuid" "$kernel" "$boot_kit_dir" "$backup_file" "$target_file" > "${boot_kit_dir}/GUIDE.txt"
    generate_recovery_script_text "$ts" "$backup_file" "$target_file" "$kernel" > "${boot_kit_dir}/restore.sh"
    chmod +x "${boot_kit_dir}/restore.sh"

    ln -sfn "$ts" "${WARDEN_ROOT_UNLOCK_BOOT_DIR}/latest"
    ln -sfn "$ts" "${WARDEN_ROOT_UNLOCK_ROOT_DIR}/latest"

    log_line "ROOT-UNLOCK: created recovery kit ${ts} (backup: ${backup_file}, guide/script: ${boot_kit_dir})"

    prune_recovery_kits "$WARDEN_ROOT_UNLOCK_BOOT_DIR" "$WARDEN_ROOT_UNLOCK_RETAIN"
    prune_recovery_kits "$WARDEN_ROOT_UNLOCK_ROOT_DIR" "$WARDEN_ROOT_UNLOCK_RETAIN"

    printf '%s' "$ts"
}

# --- Enable/Disable sequencing ------------------------------------------
#
# current_initramfs_path — the current kernel's initramfs image path.
# Wrapped in its own function (rather than inlined at each call site)
# so it's one obvious place to override for tests.
current_initramfs_path() {
    printf '/boot/initrd.img-%s' "$(uname -r)"
}

# is_root_unlock_enabled — true if clevis-initramfs is installed. Used
# to redirect Enable to Add/Rotate instead of redoing setup once
# already configured.
is_root_unlock_enabled() {
    is_pkg_installed clevis-initramfs
}

# install_clevis_initramfs_and_regenerate — installs clevis-initramfs
# (idempotent) and regenerates the current kernel's initramfs.
#
# Must run BEFORE binding any pin, not after: a TPM2 binding seals
# against the TPM's current PCR values at bind time, and regenerating
# the initramfs can itself change what's measured into those PCRs
# (depending on the PCR bank in use). Binding first and regenerating
# second risks the regeneration immediately invalidating the seal it
# just created -- everything would look correctly configured right up
# until the first real reboot silently falls back to the passphrase
# prompt. See docs/future-work.md's "Ordering matters" section.
install_clevis_initramfs_and_regenerate() {
    ensure_pkg_installed clevis-initramfs
    run_cmd "regenerate initramfs for $(uname -r)" -- update-initramfs -u -k "$(uname -r)"
}

# any_tang_address_is_local <pin_config_json> — true if any Tang URL
# embedded in <pin_config_json> (a plain tang pin, or an sss pin
# nesting tang addresses) resolves to this host itself.
any_tang_address_is_local() {
    local pin_config="$1" url host
    while IFS= read -r url; do
        [[ -n "$url" ]] || continue
        host="$(python3 -c '
import sys
from urllib.parse import urlparse
print(urlparse(sys.argv[1]).hostname or "")
' "$url" 2>/dev/null)"
        [[ -n "$host" ]] || continue
        is_local_address "$host" && return 0
    done < <(python3 -c '
import json, sys
data = json.loads(sys.argv[1])
urls = []
if "url" in data:
    urls.append(data["url"])
for pin in data.get("pins", {}).get("tang", []):
    if "url" in pin:
        urls.append(pin["url"])
print("\n".join(urls))
' "$pin_config" 2>/dev/null)
    return 1
}

# --- Menu 13 actions -----------------------------------------------------
#
# Deliberately not wired into bin/warden's main menu until the full
# action set (Enable/Add/Remove/Rotate/Status/Snapshot/Disable) is
# built and tested -- never expose a half-finished menu 13.

# root_unlock_action_enable — first-time setup.
root_unlock_action_enable() {
    if is_root_unlock_enabled; then
        warden_msg "Already enabled" "Root-drive unlock is already configured on this host. Use Add to bind an additional pin, or Rotate to replace the existing one."
        return 0
    fi

    local root_dev
    root_dev="$(resolve_root_luks_device)"
    if [[ -z "$root_dev" ]]; then
        warden_msg "Root is not LUKS-encrypted" "This feature enrols Clevis onto an existing LUKS-encrypted root filesystem -- it does not encrypt an unencrypted root in place. This system's root does not appear to be LUKS-encrypted, so there is nothing to enable here."
        return 0
    fi

    if ! is_boot_separate_from_root; then
        warden_msg "Unusual boot layout" "This system's /boot does not appear to be a separate partition from root -- it may live inside the encrypted volume itself. That's a less common layout this feature has not been verified against (GRUB would need cryptodisk support already configured, which Warden does not set up). Refusing to proceed automatically -- investigate your GRUB configuration manually first if you want to continue."
        return 0
    fi

    local root_uuid
    root_uuid="$(uuid_for_device "$root_dev")"

    if ! warden_yesno "Root device" "Root filesystem is backed by: ${root_dev}\nUUID: ${root_uuid}\n\nThis is the device root-drive unlock will apply to.\n\nProceed?"; then
        return 0
    fi

    if ! warden_yesno "Recovery media check" "Do you have bootable recovery/rescue media for THIS machine ready right now (e.g. a live Ubuntu USB/ISO)?\n\nIf not, stop here and prepare one before continuing -- this changes how the machine boots, and rescue media is the way back in if something goes wrong." ; then
        warden_msg "Cancelled" "Prepare recovery media first, then come back to this menu. No changes were made."
        return 0
    fi

    local pin_type
    pin_type="$(warden_menu "Pin type" "Which unlock method should root use?" \
        tpm2 "TPM2 chip on this machine (no network needed, most reliable for root)" \
        tang "A LAN-reachable Tang server (never Tailscale -- cannot work for root)")" || return 0

    local pin_config
    if [[ "$pin_type" == "tpm2" ]]; then
        if ! is_tpm2_present; then
            warden_msg "No TPM2 device found" "Neither /dev/tpm0 nor /dev/tpmrm0 exists on this host. Cannot offer a TPM2 pin here."
            return 0
        fi
        if ! is_pkg_installed clevis-tpm2; then
            warden_msg "clevis-tpm2 not installed" "A TPM2 chip is present, but the clevis-tpm2 package (which actually implements the tpm2 pin) isn't installed. Install it from menu 1 first."
            return 0
        fi
        pin_config="$(build_tpm2_pin_config)"
    else
        local host_port host port url
        host_port="$(whiptail --inputbox "Tang server address for root unlock (host:port).\n\nMust be reachable over plain LAN networking -- a Tailscale-routed address can never work here (tailscaled cannot run before root is mounted), and neither can a Tang server on this same machine (it can't start until root already is)." 14 74 3>&1 1>&2 2>&3)" || return 0
        IFS=$'\t' read -r host port < <(parse_host_port "$host_port")
        if is_local_address "$host"; then
            warden_msg "Refused: same-host Tang" "'${host}' resolves to this machine itself. A Tang server on the SAME host as the root filesystem it's unlocking can never work: Tang runs as a systemd service that can't start until root is already mounted, and root can't mount until it's unlocked. This isn't a reachability problem, it's a bootstrapping deadlock. Point this at a Tang server on a DIFFERENT machine, reachable over plain LAN networking."
            return 0
        fi
        url="http://${host}:${port}"
        local reach
        reach="$(check_tang_reachability "$url")"
        if ! warden_yesno "Tang reachability" "${url}: ${reach}\n\nProceed anyway?"; then
            return 0
        fi
        pin_config="$(build_tang_pin_config "$url")"
    fi

    local passphrase
    passphrase="$(whiptail --passwordbox "Enter this device's EXISTING LUKS passphrase, to authorise adding the new Clevis binding:" 12 70 3>&1 1>&2 2>&3)" || return 0

    local initramfs_path
    initramfs_path="$(current_initramfs_path)"

    if warden_yesno "Preview" "This will:\n\n1. Back up the current initramfs (${initramfs_path})\n2. Install clevis-initramfs and regenerate the initramfs for kernel $(uname -r)\n3. Bind Clevis to ${root_dev} using the ${pin_type} pin\n\nThe existing LUKS passphrase is never touched or removed. Unlike other menus, this cannot be test-unlocked live -- root's device is always in use while Warden runs, so an actual reboot is the only real proof.\n\nShow this as a dry-run first (no changes made)?"; then
        local saved_dry_run="${WARDEN_DRY_RUN}"
        WARDEN_DRY_RUN=1
        create_root_unlock_recovery_kit "$initramfs_path" >/dev/null
        install_clevis_initramfs_and_regenerate
        run_clevis_luks_bind "$root_dev" "$passphrase" "$pin_type" "$pin_config" >/dev/null
        WARDEN_DRY_RUN="$saved_dry_run"
        if ! warden_yesno "Proceed?" "Proceed with the real changes now?"; then
            return 0
        fi
    fi

    local kit_ts
    kit_ts="$(create_root_unlock_recovery_kit "$initramfs_path")"
    if [[ -z "$kit_ts" ]]; then
        warden_msg "Could not create recovery kit" "Backing up the current initramfs failed -- check the session log at ${WARDEN_LOG_FILE}. Refusing to proceed without a backup in place first."
        return 0
    fi

    if ! install_clevis_initramfs_and_regenerate; then
        warden_msg "Initramfs regeneration failed" "Check the session log at ${WARDEN_LOG_FILE}. The recovery kit at ${WARDEN_ROOT_UNLOCK_BOOT_DIR}/${kit_ts} still has the pre-change backup if you need it."
        return 0
    fi

    if ! run_clevis_luks_bind "$root_dev" "$passphrase" "$pin_type" "$pin_config" >/dev/null; then
        warden_msg "Bind failed" "clevis luks bind did not succeed. Check the session log at ${WARDEN_LOG_FILE}. The initramfs hook is installed, but no Clevis binding was added -- the passphrase is still the only way to unlock this device."
        return 0
    fi

    # Deliberately no test_unlock_and_cleanup here, unlike every other
    # enrolment path in Warden. Confirmed on real hardware: root's LUKS
    # device is *always* already open/mounted whenever Warden itself is
    # running (Warden runs from the booted OS on that very device), so
    # cryptsetup refuses a second mapping outright ("Cannot use device
    # ... which is in use") every single time, unlike the ZFS case
    # (test_unlock_and_cleanup_zfs) where the device is only
    # *sometimes* already open and an export/close/reopen dance can
    # work around it. There is no equivalent workaround for root: you
    # cannot unmount a running system's own root filesystem to test it.
    # clevis luks bind's own successful exit is the only automated
    # signal available here -- a real reboot is the only actual proof.
    warden_msg "Enable complete" "Root-drive unlock is enabled: clevis luks bind succeeded for the ${pin_type} pin on ${root_dev}.\n\nIMPORTANT: unlike every other binding in Warden, this could NOT be verified with a live test-unlock -- root's own device is always in use while Warden is running, so there is no way to safely test it without an actual reboot. A successful bind here is not the same guarantee menus 4/5/8 give you.\n\nDo not close your only access to this machine until you have rebooted and confirmed it unlocks correctly.\n\nYour recovery kit:\n${WARDEN_ROOT_UNLOCK_BOOT_DIR}/${kit_ts} (guide + script)\n${WARDEN_ROOT_UNLOCK_ROOT_DIR}/${kit_ts} (initramfs backup)\n\nRead the guide there before rebooting."
}

